import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import studentsRouter from "./students";
import questsRouter from "./quests";
import interviewRouter from "./interview";
import testRouter from "./test";
import jobsRouter from "./jobs";
import leaderboardRouter from "./leaderboard";
import aiRouter from "./ai";
import anthropicRouter from "./anthropic";
import courseRouter from "./course";
import courseVideoRouter from "./courseVideo";
import courseLinkRouter from "./courseLink";
import opportunitiesRouter from "./opportunities";
import profileRouter from "./profile";
import tpoRouter from "./tpo";
import tpoAuthRouter from "./tpoAuth";
import driveCheckRouter from "./driveCheck";
import resumeRouter from "./resume";
import recruiterRouter from "./recruiter";
import adminRouter from "./admin";
import collegesRouter from "./colleges";
import activityLogRouter from "./activityLog";
import dailyTasksRouter from "./dailyTasks";
import pipelineRouter from "./pipeline";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(studentsRouter);
router.use(profileRouter);
router.use(questsRouter);
router.use(interviewRouter);
router.use(testRouter);
router.use(jobsRouter);
router.use(leaderboardRouter);
router.use(aiRouter);
router.use(anthropicRouter);
router.use(courseRouter);
router.use(courseVideoRouter);
router.use(courseLinkRouter);
router.use(opportunitiesRouter);
router.use(tpoAuthRouter);
router.use(tpoRouter);
router.use(driveCheckRouter);
router.use(resumeRouter);
router.use(recruiterRouter);
router.use(adminRouter);
router.use(collegesRouter);
router.use(activityLogRouter);
router.use(dailyTasksRouter);
router.use(pipelineRouter);

export default router;
